name: flutter_web_application_1
description: "A new Flutter project."

version: 1.0.1+2

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/abi/ERC20.json
